sudo: required
addons:
  chrome: stable
cache: yarn
language: node_js
node_js:
- "10"

branches:
  only:
  - master

before_script:
- npm install -g @angular/cli

script:
- npm build
- npm run citest
