sudo: required
addons:
  chrome: stable
language: node_js
node_js: "10"
cache: yarn

branches:
  only:
  - master

before_script:
- npm install -g @angular/cli

script:
- npm run build
- npm run citest
